---
version: "3"
services:
 devopsdb:
   container_name: dbcontainer
   image: ramyaakula7/myrepo:dbimage
   ports:
     - "3306:3306"
   volumes:
     - db-data:/var/lib/mysql
 application:
   container_name: appcontainer
   image: ramyaakula7/myrepo:appimage
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
     
     
 volumes:
  db-data:
